export default {
  fieldset: 'fieldset.html',
  button: 'input.html',
  checkbox: 'checkbox.html',
  color: 'input.html',
  date: 'input.html',
  datetime: 'input.html',
  'datetime-local': 'input.html',
  email: 'input.html',
  month: 'input.html',
  number: 'input.html',
  password: 'input.html',
  radios: 'radios.html',
  checkboxes: 'checkboxes.html',
  select: 'select.html',
  range: 'input.html',
  file: 'file.html',
  search: 'input.html',
  submit: 'submit.html',
  tel: 'input.html',
  textarea: 'textarea.html',
  text: 'input.html',
  time: 'input.html',
  url: 'input.html',
  week: 'input.html'
};
